import numpy as np

OLED_WIDTH: int
OLED_HEIGHT: int

def take_array(arr: np.ndarray) -> np.ndarray: ...
def init(arr: np.ndarray) -> None: ...
def deinit() -> None: ...
def get_array() -> np.ndarray: ...
